### ISSUE TITLE
RuntimeError: Either 'SQLALCHEMY_DATABASE_URI' or 'SQLALCHEMY_BINDS' must be set.

### ISSUE THREAD

**Issue by daarisameen** [SaiSatya16/Grocery-Store-V2#1]
1. Install required dependencies: pip install -r requirements.txt - RAN SUCCESSFULLY

2. Create a SQLite3 database by running: python upload_initial_data.py - THROWS ERROR*

ERROR*:
raise RuntimeError(
RuntimeError: Either 'SQLALCHEMY_DATABASE_URI' or 'SQLALCHEMY_BINDS' must be set.

**Comment by SaiSatya16** [comment]
`export DATABASE_URL=sqlite:///database.sqlite3`
run this command in your terminal before running `python upload_initial_data.py`
